version: '3'
services:
  "web-application":
    build: "./web-application"
    ports:
      - "8080:8080"
      - "9229:9229"
      - "3000:3000"
    volumes:
      - "./web-application/src:/web-application/src"
    depends_on:
      - database
      - redis
      - postgres
  database:
    build: ./database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=abc123
      - MYSQL_DATABASE=plantDatabase
  "redis":
    build: "./redis"
    ports:
     - "6379:6379"
  "postgres":
    build: "./postgres"
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=abc123
  "spa":
    build: "./spa"
    ports:
    - "6001:6001"
    volumes:
      - "./spa/spa-src:/spa/spa-src"